config/routes.rb
I2X::Application.routes.draw do

  root  'home#index'
  get 'home' => 'home/index'
  get "home/index"

  get "about/index"

  resources :agents
  get "agents/partials/:identifier", to: 'agents#partials'  		# what is this?
  get "agents/import/:identifier", to: "agents#import"      		# import from JSON file
  get "agents/:id/get", to: "agents#get"            		        # load agent as JSON
  get "agents/add/:identifier", to: "agents#add"            		# add sample agent to user
  get "agents/:id/execute", to: "agents#execute"                # launch on-demand agent execution
  
  
  resources :caches

  get "contact/index", to: 'contact#index'

  get 'dashboard',to: redirect('/integrations')

  get "delivery/get"
  post "delivery/post"
  get "delivery/go"

  get "docs", to: 'docs#index'
  get 'docs/:section/:topic', to: 'docs#show'

  resources :events
  resources :events do
    get 'page/:page', :action => :index, :on => :collection
  end

  get "files/get/:filename", to: "files#get"
  get "files/delete/:filename", to: "files#delete"
  get "files/index"

  post "fluxcapacitor/generate_key", to: 'flux_capacitor#generate_key'
  post "fluxcapacitor/remove_key", to: 'flux_capacitor#remove_key'
  post "fluxcapacitor/validate_key", to: 'flux_capacitor#validate_key'
  post 'fluxcapacitor/verify', to: 'flux_capacitor#verify'
  get 'fluxcapacitor/ping/:ping', to: 'flux_capacitor#ping'
  post 'fluxcapacitor/ping', to: 'flux_capacitor#ping'
  post 'fluxcapacitor/generate_client', to: 'flux_capacitor#generate_client'
  get 'fluxcapacitor/generate_client', to: 'flux_capacitor#generate_client'
  post 'fluxcapacitor/agents/:id/update_meta', to: 'flux_capacitor#agent_update_meta'
  
  get "helper/index"

  resources :integrations
  post "integrations/:id/save", to: 'integrations#save'
  get "integrations/add/:agent/:template", to: 'integrations#add'
  get "integrations/:id/execute", to: 'integrations#execute'      # execute integration on-demand

  get "postman/load/:publisher/:identifier", to: "postman#load"
  get "postman/go/:identifier", to: 'postman#go'
  post "postman/deliver/:identifier", to: "postman#deliver"
  post "postman/:key", to: "postman#action"

  post "push/:identifier", to: "push#checkup"

  resources :seeds

  resources :templates
  get "templates/:id/get", to: "templates#get"            # load template as JSON
  post "templates/new"
  get "templates/start"
  get "templates/add/:identifier", to: 'templates#add'            # add template from samples to user
  

  get "tester/regex", to: 'tester#regex'
  get "tester/agent/:identifier", to: 'tester#agent'
  get 'tester/dropbox', to: 'tester#dropbox'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  devise_scope :user do get "users/sign_out" => 'devise/sessions#destroy' end
  get "sign_up", :to => "devise/registrations#new"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'documentation' => 'documentation/index'
  get 'contact' => 'contact/index'
  get "faq" => 'faq/index'
  get "how_to" => 'how_to/index'
  get 'reference' => 'reference/index'

  get '/i2x/images/*all', to: redirect('/images/%{all}.png')

end

app/views/templates/_form.html.erb
<%= form_for(@template, :remote => true) do |f| %>
<% if @template.errors.any? %>
<div id="error_explanation" class="alert-box alert">
  <h2><%= pluralize(@template.errors.count, "error") %>
    prohibited this template from being saved:</h2>
    <ul>
      <% @template.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :title, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.text_area :title, :tabindex => autotab %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :help, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.text_area :help, :tabindex => autotab %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :publisher, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.select :publisher, options_for_select([['SQL', 'sql'], ['URL', 'url'], ['Email', 'mail'], ['File','file'], ['Dropbox','dropbox']], {:selected => (@template.publisher.nil?) ? 'url' : @template.publisher}), {:tabindex => autotab} %>
    </div>
  </div>
  <!-- Publisher properties -->
  <div id="publisher_content">
    <%= render :partial => "templates/payload_#{@template.publisher}", locals: {:template => @template} %>
  </div>
  <div class="row">
    <div class="small-2 columns right">
      <%= f.submit 'Save', :class => "button right small right radius success", :tabindex => autotab, :id => 'save_template' %>
    </div>
  </div>
  <% end %>

app/views/templates/_new.html.erb
<%= form_for(@template, :remote => true) do |f| %>
<% if @template.errors.any? %>
<div id="error_explanation" class="alert-box alert">
  <h2><%= pluralize(@template.errors.count, "error") %>
    prohibited this template from being saved:</h2>
    <ul>
      <% @template.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <h4 class="subheader">Template Properties</h4>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :identifier, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.text_field :identifier, :tabindex => autotab, :autofocus => true, :required => '' %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :title, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.text_area :title, :tabindex => autotab, :required => '' %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :help, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.text_area :help, :tabindex => autotab %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :publisher, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
     <% if current_user.has_dropbox %>
     <%= f.select(:publisher, options_for_select([['SQL', 'sql'], ['URL', 'url'],['Email', 'mail'], ['File','file'],['Dropbox','dropbox']], {:selected => 'url'}), :tabindex => autotab) %>
     <% else %>
     <%= f.select(:publisher, options_for_select([['SQL', 'sql'], ['URL', 'url'],['Email', 'mail'], ['File','file']], {:selected => 'url'}), :tabindex => autotab) %>
     <% end %>

      
    </div>
  </div>
  <div id="publisher_content">
    <%= render :partial => "templates/payload_url", locals: {:template => @template} %>
  </div>
  <div class="actions">
    <%= f.submit 'Create', :class => 'button right success small radius', :tabindex => autotab %>
  </div>
  <% end %>

app/views/templates/_payload_dropbox.html.erb
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_dropbox_method" class="right inline">Method</label>
  </div>
  <div class="small-9 columns">
   <%= select_tag 'template[method]', options_for_select([['Append', 'append'], ['Create', 'create'], ['Delete', 'delete']], {:selected => template.method}), {:id => 'publisher_dropbox_method', :tabindex => autotab} %>
 </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_dropbox_uri" class="right inline">URI</label>
  </div>
  <div class="small-9 columns">
    <input type="url" required id="publisher_dropbox_uri" tabindex="<%= autotab %>" value="<%= template.uri.nil? ? '' : template.uri %>" name="template[uri]" placeholder="E.g.: file:///home/user/this.csv" />
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_dropbox_content" class="right inline">Content</label>
  </div>
  <div class="small-9 columns">
    <textarea type="text" required id="publisher_dropbox_content" tabindex="<%= autotab %>" name="template[content]" placeholder="E.g.: %{i2x.date},%{id}\n"><%= template.content.nil? ? '' : template.content %></textarea>
  </div>
</div>

app/views/templates/_payload_file.html.erb
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_file_method" class="right inline">Method</label>
  </div>
  <div class="small-9 columns">
   <%= select_tag 'template[method]', options_for_select([['Append', 'append'], ['Create', 'create'], ['Delete', 'delete']], {:selected => template.method}), {:id => 'publisher_file_method', :tabindex => autotab} %>
 </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_file_uri" class="right inline">URI</label>
  </div>
  <div class="small-9 columns">
    <input type="text" required id="publisher_file_uri" tabindex="<%= autotab %>" value="<%= template.uri.nil? ? '' : template.uri %>" name="template[uri]" placeholder="E.g.: file:///home/user/this.csv" />
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_file_content" class="right inline">Content</label>
  </div>
  <div class="small-9 columns">
    <textarea type="text" required id="publisher_file_content" tabindex="<%= autotab %>" name="template[content]" placeholder="E.g.: %{i2x.date},%{id}\n"><%= template.content.nil? ? '' : template.content %></textarea>
  </div>
</div>

app/views/templates/_payload_mail.html.erb
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_mail_host" class="right inline">To</label>
  </div>
  <div class="small-9 columns">
    <input type="text" id="publisher_mail_host" tabindex="<%= autotab %>" value="<%= template.to.nil? ? '' : template.to %>" name="template[to]" required placeholder="E.g.: john@gmail.com" />
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_mail_cc" class="right inline">CC</label>
  </div>
  <div class="small-9 columns">
   <input type="text" id="publisher_mail_cc" tabindex="<%= autotab %>" value="<%= template.cc.nil? ? '' : template.cc %>" name="template[cc]" placeholder="E.g.: alice@gmail.com" />
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_mail_bcc" class="right inline">BCC</label>
  </div>
  <div class="small-9 columns">
    <input type="text" id="publisher_mail_bcc" tabindex="<%= autotab %>" value="<%= template.bcc.nil? ? '' : template.bcc %>" name="template[bcc]" placeholder="E.g.: bob@gmail.com" />
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_mail_subject" class="right inline">Subject</label>
  </div>
  <div class="small-9 columns">
    <input type="text" id="publisher_mail_subject" required tabindex="<%= autotab %>" value="<%= template.subject.nil? ? '' : template.subject %>" name="template[subject]" placeholder="E.g.: Hello from i2x" />
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_mail_message" class="right inline">Message</label>
  </div>
  <div class="small-9 columns">
    <textarea id="publisher_mail_message" required tabindex="<%= autotab %>"  name="template[message]"placeholder="E.g.: INSERT INTO..."><%= template.message.nil? ? '' : template.message %></textarea>
  </div>
</div>

app/views/templates/_payload_url.html.erb
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_url_method" class="right inline">Method</label>
  </div>
  <div class="small-9 columns">
    <%= select_tag 'template[method]', options_for_select([['POST', 'post'], ['GET', 'get']], {:selected => (template.method.nil?) ? 'post' : template.method}), {:id => 'publisher_url_method', :tabindex => autotab} %>
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_url_uri" class="right inline">URI</label>
  </div>
  <div class="small-9 columns">
    <input type="url" tabindex="<%= autotab %>" value="<%= template.uri.nil? ? '' : template.uri %>" name="template[uri]" required id="publisher_url_uri" placeholder="E.g.: https://bioinformatics.ua.pt/i2x/..." />
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_url_message" class="right inline">Message type</label>
  </div>
  <div class="small-9 columns">
    <%= select_tag 'template[message]', options_for_select([['Form data', 'form'], ['Text (text/plain)', 'text/plain'], ['JSON (application/json)', 'application/json'], ['JavaScript', 'application/javascript'], ['XML (application/xml)', 'application/xml'], ['XML (text/xml)', 'text/xml'], ['HTML (text/html)', 'text/html']], {:selected => (template.message.nil?) ? 'application/json' : template.message}), {:id => 'publisher_url_message', :tabindex => autotab} %>
  </div>
</div>
<div class="row" id="publisher_url_content_box">
  <div class="small-3 columns">
    <label for="publisher_url_content" class="right inline">Content</label>
  </div>
  <div class="small-9 columns">
    <textarea tabindex="<%= autotab %>" name="template[content]" id="publisher_url_content" placeholder="E.g.: {'id':'123', ...}"><%= template.content.nil? ? '' : template.content %></textarea>
  </div>
</div>
<!-- Conditional POST parameters start -->
<div id="publiser_url_post_params">
  <input type="hidden" id="url_post_params_hidden" name="template[selectors]" value='<%= @template.selectors.nil? ? '[]' : @template.selectors %>' />

  <% i = 1 %>
  <% unless template.selectors.nil? then %>
  <% JSON.parse(template.selectors).each do |selector| %>
  <% selector.each do |k,v| %>
  <div class="row">
    <div class="url_post_params_<%= i %> publisher_url_post_params_new_<%= i %>">
      <div class="small-3 columns left">
        <label class="right inline">Parameter <%= i %></label>
      </div>
      <div class="small-4 columns url_post_params_key_<%= i %>">
        <input id="publisher_url_post_params_key_<%= i %>" data-id="<%= i %>" type="text" disabled class="disabled publisher_url_post_params_key" value="<%= k %>" />
      </div>
      <div class="small-4 columns url_post_params_value_<%= i %>">
        <input id="publisher_url_post_params_value_<%= i %>" type="text" placeholder="E.g.: id" disabled class="disabled" value="<%= v %>" />
      </div>
      <div class="small-1 columns">
        <a href="#" data-id="<%= i %>" class="remove right publisher_url_params_remove">Remove</a>
      </div>
    </div>
  </div>
  <% i = i +1 %>
  <% end %>
  <% end %>
  <% end %>
</div>

<div class="row">
  <div class="small-3 columns">
    <label class="right inline">New parameter</label>
  </div>
  <div class="small-4 columns">
    <input type="text" class="publisher_url_post_params_key " tabindex="<%= autotab %>" data-id="<%= i %>" placeholder="Key" id="publisher_url_post_params_key_<%= i %>" />
  </div>
  <div class="small-4 columns">
    <input type="text" class="publisher_url_post_params_value " tabindex="<%= autotab %>" data-id="<%= i %>" placeholder="Value" id="publisher_url_post_params_value_<%= i %>" />
  </div>
  <div class="small-1 columns">
    <a href="#" data-id="<%= i %>" class="button tiny radius publisher_url_post_params_add" tabindex="<%= autotab %>" id="publisher_url_post_params_button_<%= i %>">Add</a>
  </div>
</div>

app/views/templates/_show.html.erb
<div class="row">
  <div class="small-11 columns left">
    <span class="label secondary radius"><small>Updated <%= time_ago_in_words(template.updated_at) %> ago</small></span>
    <span class="label secondary radius"><small>Last delivery <%= template.last_execute_at.nil? ? 'Not executed' : time_ago_in_words(template.last_execute_at) +' ago' %></small></span>
  </div>
  <div class="small-1 columns right text-right">
   <span class="has-tip tip-top radius" data-tooltip title="Edit <%= template.title %>"><%= link_to '', edit_template_path(template), :class => "icon-settings xl-icon", :title => "Edit #{template.title}" %></span>
 </div>
</div>
<br />
<div class="row">
  <div class="small-2 columns">
    <div class="agent-hl">
      <div class="big center">
       <span class="has-tip tip-top radius" data-tooltip title="Events: i2x delivered this template <%= template.count %> times"><%= template.count %></span>
      </div>
      <h5 class="center icon-list xl-icon"></h5>
    </div>
    <div class="agent-hl">
      <div class="big center">
        <span class="has-tip tip-top radius" data-tooltip title="Delivery: this template delivers '<%= template.publisher %>'' output"><%= template.publisher %></span>
      </div>
      <h5 class="center icon-publisher xl-icon"></h5>
    </div>
  </div>
  <div class="small-10 columns">
    <div class="row">
      <h4 class="subheader">Help</h4>
      <%= template.help %>
    </div>
    <hr>
    <div class="row">
      <h4 class="subheader">Publisher</h4>
      <% if template.publisher == 'sql' then %>
      <%= render partial: "templates/show_sql", locals: {:template => template}%>
      <% end %>
      <% if template.publisher == 'file' then %>
      <%= render partial: "templates/show_file", locals: {:template => template}%>
      <% end %>
      <% if template.publisher == 'url' then %>
      <%= render partial: "templates/show_url", locals: {:template => template}%>
      <% end %>
      <% if template.publisher == 'mail' then %>
      <%= render partial: "templates/show_mail", locals: {:template => template}%>
      <% end %>
      <% if template.publisher == 'dropbox' then %>
      <%= render partial: "templates/show_dropbox", locals: {:template => template}%>
      <% end %>
    </div>
  </div>
</div>

app/views/templates/_show_dropbox.html.erb
<div class="row">
  <div class="small-1 columns">
    <div class="right inline icon-properties xl-icon has-tip radius" data-tooltip class="has-tip" title="Connection Details">&nbsp;</div>
  </div>
  <div class="small-11 columns">
    <div class="row">
      <div class="small-2 columns">
        <strong class="right inline">URI</strong>
      </div>
      <div class="small-10 columns">
        <%= highlight_variables(template[:payload][:uri]) %>
      </div>
    </div>
    <div class="row">
      <div class="small-2 columns">
        <strong class="right inline">Method</strong>
      </div>
      <div class="small-10 columns">
        <%= highlight_variables(template[:payload][:method]) %>
      </div>
    </div>
    <div class="row">
      <div class="small-2 columns">
        <strong class="right inline">Content</strong>
      </div>
      <div class="small-10 columns">
        <%= highlight_variables(template[:payload][:content]) %>
      </div>
    </div>
  </div>
</div>

app/views/templates/_show_file.html.erb
<div class="row">
  <div class="small-1 columns">
    <div class="right inline icon-properties xl-icon has-tip radius" data-tooltip class="has-tip" title="Connection Details">&nbsp;</div>
  </div>
  <div class="small-11 columns">
    <div class="row">
      <div class="small-2 columns">
        <strong class="right inline">URI</strong>
      </div>
      <div class="small-10 columns">
        <%= highlight_variables(template[:payload][:uri]) %>
      </div>
    </div>
    <div class="row">
      <div class="small-2 columns">
        <strong class="right inline">Method</strong>
      </div>
      <div class="small-10 columns">
        <%= highlight_variables(template[:payload][:method]) %>
      </div>
    </div>
    <div class="row">
      <div class="small-2 columns">
        <strong class="right inline">Content</strong>
      </div>
      <div class="small-10 columns">
        <%= highlight_variables(template[:payload][:content]) %>
      </div>
    </div>
  </div>
</div>

app/views/templates/_show_integration.html.erb
<div class="row">
	<div class="small-12 medium-12 large-12 columns"><h4 class="subheader"><%= link_to template.title, template %></h4></div>
	<div class="small-12 medium-8 large-8 columns left">
		<span class="label secondary radius icon-publisher"><%= template.publisher %></span>
	</div>
	<div class="small-12 medium-4 large-4 columns right">
		<a class="remove right remove_template_integration has-tip" data-tooltip data-id="<%= template.id %>" title="Detach <%= template.identifier %>">Remove template</a>
	</div>
</div>

app/views/templates/edit.html.erb
<% content_for :javascript_includes do %>
<%= javascript_include_tag "#{ENV['APP_HOST']}templates/new.js" %>
<% end %>

<% content_for :title, "Edit #{@template.title} - #{ENV["APP_TITLE"]}" %>
<ul class="breadcrumbs">
  <li><a href="<%= root_url %>">Home</a></li>
  <li><%= link_to 'Templates', templates_path %></li>
  <li><%= link_to @template.title, @template %></li>
  <li class="current">Edit <%= @template.title %></li>
</ul>
<h1>Editing <strong><%= @template.title %></strong> template</h1>

<%= render 'form' %>

<div class="row">
  <div class="small-1 columns right">
    <%= link_to 'Remove', @template, :class => 'remove right', method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/templates/new.html.erb
<% content_for :javascript_includes do %>
<%= javascript_include_tag "#{ENV['APP_HOST']}templates/new.js" %>
<% end %>

<% content_for :title, "New template - #{ENV["APP_TITLE"]}" %>
<ul class="breadcrumbs">
  <li><a href="<%= root_url %>">Home</a></li>
  <li><%= link_to 'Templates', templates_path %></li>
  <li class="current">New template</li>
</ul>
<h1>New template</h1>
<%= render 'new' %>

app/views/templates/show.html.erb
<% content_for :title, "#{@template.title} - #{ENV["APP_TITLE"]}" %>
<ul class="breadcrumbs">
  <li><a href="<%= root_url %>">Home</a></li>
  <li><%= link_to 'Templates', templates_path %></li>
  <li class="current"><%= @template.title %></li>
</ul>
<div class="row">
  <div class="small-12 columns">
    <h1><%= @template.title %></h1>
  </div>
</div>
<%= render :partial => "templates/show", locals: {:template => @template} %>

app/views/templates/start.html.erb
<h1>New template</h1>
<%= form_for(@template) do |f| %>
<% if @template.errors.any? %>
<div id="error_explanation" class="alert-box alert">
  <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

  <ul>
    <% @template.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<fieldset>
  <legend>Template Properties</legend>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :identifier, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.text_field :identifier, :tabindex => 1, :autofocus => true %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :title, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.text_area :title, :tabindex => 2 %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :help, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= f.text_area :help, :tabindex => 3 %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :publisher, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <%= select_tag(:publisher, options_for_select([['SQL', 'sql'], ['URL', 'url'], ['File','file']], {:selected => 'sql'}), :tabindex => 4) %>  
    </div>  
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :variables, :class => 'right inline' %>
    </div>
    <div class="small-9 columns">
      <div class="row collapse" id="template_variables_include">
      </div>
      <div class="row collapse">
        <div class="small-10 columns">
          <input type="text" class="template_variable_text template_variables_base" tabindex="5" data-id="1" placeholder="E.g.: id" id="template_variables_text_1">
        </div>
        <div class="small-2 columns">
          <a href="#" data-id="1" class="button prefix template_variables_add" tabindex="6" id="template_variables_button_1">Add</a>
        </div>
    </div>
  </div>
</fieldset>
<div class="publisher_sql">
  <fieldset><legend>SQL Publisher Properties</legend>
    <div class="row">
     <div class="small-3 columns">
      <label for="publisher_sql_server" class="right inline">Server</label>
    </div>
    <div class="small-9 columns">
      <select id="publisher_sql_server" tabindex="8">
        <option selected="selected" value="mysql">MySQL</option>
        <option value="sqlserver">SQL Server</option>
        <option value="postgres">Postgres</option>
        <option value="sqlite">SQLite</option>
      </select>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <label for="publisher_sql_host" class="right inline">Host</label>
    </div>
    <div class="small-9 columns">
      <input type="text" id="publisher_sql_host" tabindex="9" placeholder="E.g.: localhost">
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <label for="publisher_sql_port" class="right inline">Port</label>
    </div>
    <div class="small-9 columns">
      <input type="number" id="publisher_sql_port" tabindex="10" placeholder="E.g.: 3306">
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <label for="publisher_sql_database" class="right inline">Database</label>
    </div>
    <div class="small-9 columns">
      <input type="text" id="publisher_sql_database" tabindex="11" placeholder="E.g.: i2x">
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <label for="publisher_sql_username" class="right inline">Username</label>
    </div>
    <div class="small-9 columns">
      <input type="text" id="publisher_sql_username" tabindex="12" placeholder="E.g.: root">
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <label for="publisher_sql_password" class="right inline">Password</label>
    </div>
    <div class="small-9 columns">
      <input type="text" id="publisher_sql_password" tabindex="13" placeholder="E.g.: 12345">
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <label for="publisher_sql_query" class="right inline">Query</label>
    </div>
    <div class="small-9 columns">
      <textarea id="publisher_sql_query" tabindex="14" placeholder="E.g.: INSERT INTO..."></textarea>
    </div>
  </div>
</fieldset>
</div>
<div class="field publisher_url">
 <fieldset><legend>URL Publisher Properties</legend>
  <div class="row">
   <div class="small-3 columns">
    <label for="publisher_url_method" class="right inline">Method</label>
  </div>
  <div class="small-9 columns">
    <select id="publisher_url_method" tabindex="15">
      <option selected="selected" value="get">GET</option>
      <option value="post">POST</option>
      <option value="update">UPDATE</option>
      <option value="delete">DELETE</option>
    </select>
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_url_uri" class="right inline">URI</label>
  </div>
  <div class="small-9 columns">
   <input type="url" tabindex="16" id="publisher_url_uri" placeholder="E.g.: https://bioinformatics.ua.pt/i2x/...">
 </div>
</div>
</fieldset>
</div>
<div class="field publisher_file">
 <fieldset><legend>File Publisher Properties</legend>
  <div class="row">
   <div class="small-3 columns">
    <label for="publisher_file_method" class="right inline">Method</label>
  </div>
  <div class="small-9 columns">
    <select id="publisher_file_method" tabindex="17">
      <option selected="selected" value="append">Append</option>
      <option value="create">Create</option>
      <option value="delete">Delete</option>
    </select>
  </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_file_uri" class="right inline">URI</label>
  </div>
  <div class="small-9 columns">
   <input type="url" id="publisher_file_uri" tabindex="17" placeholder="E.g.: file:///home/user/this.csv">
 </div>
</div>
<div class="row">
  <div class="small-3 columns">
    <label for="publisher_file_content" class="right inline">Content</label>
  </div>
  <div class="small-9 columns">
   <textarea type="text" id="publisher_file_content" tabindex="18" placeholder="E.g.: %{i2x.date},%{id}\n"></textarea>
 </div>
</div>
</fieldset>
</div>
<div class="actions">
  <a class="button right success" tabindex="40" id="start">Submit</a>
</div>
<% end %>