config/routes.rb
I2X::Application.routes.draw do

  root  'home#index'
  get 'home' => 'home/index'
  get "home/index"

  get "about/index"

  resources :agents
  get "agents/partials/:identifier", to: 'agents#partials'  		# what is this?
  get "agents/import/:identifier", to: "agents#import"      		# import from JSON file
  get "agents/:id/get", to: "agents#get"            		        # load agent as JSON
  get "agents/add/:identifier", to: "agents#add"            		# add sample agent to user
  get "agents/:id/execute", to: "agents#execute"                # launch on-demand agent execution
  
  
  resources :caches

  get "contact/index", to: 'contact#index'

  get 'dashboard',to: redirect('/integrations')

  get "delivery/get"
  post "delivery/post"
  get "delivery/go"

  get "docs", to: 'docs#index'
  get 'docs/:section/:topic', to: 'docs#show'

  resources :events
  resources :events do
    get 'page/:page', :action => :index, :on => :collection
  end

  get "files/get/:filename", to: "files#get"
  get "files/delete/:filename", to: "files#delete"
  get "files/index"

  post "fluxcapacitor/generate_key", to: 'flux_capacitor#generate_key'
  post "fluxcapacitor/remove_key", to: 'flux_capacitor#remove_key'
  post "fluxcapacitor/validate_key", to: 'flux_capacitor#validate_key'
  post 'fluxcapacitor/verify', to: 'flux_capacitor#verify'
  get 'fluxcapacitor/ping/:ping', to: 'flux_capacitor#ping'
  post 'fluxcapacitor/ping', to: 'flux_capacitor#ping'
  post 'fluxcapacitor/generate_client', to: 'flux_capacitor#generate_client'
  get 'fluxcapacitor/generate_client', to: 'flux_capacitor#generate_client'
  post 'fluxcapacitor/agents/:id/update_meta', to: 'flux_capacitor#agent_update_meta'
  
  get "helper/index"

  resources :integrations
  post "integrations/:id/save", to: 'integrations#save'
  get "integrations/add/:agent/:template", to: 'integrations#add'
  get "integrations/:id/execute", to: 'integrations#execute'      # execute integration on-demand

  get "postman/load/:publisher/:identifier", to: "postman#load"
  get "postman/go/:identifier", to: 'postman#go'
  post "postman/deliver/:identifier", to: "postman#deliver"
  post "postman/:key", to: "postman#action"

  post "push/:identifier", to: "push#checkup"

  resources :seeds

  resources :templates
  get "templates/:id/get", to: "templates#get"            # load template as JSON
  post "templates/new"
  get "templates/start"
  get "templates/add/:identifier", to: 'templates#add'            # add template from samples to user
  

  get "tester/regex", to: 'tester#regex'
  get "tester/agent/:identifier", to: 'tester#agent'
  get 'tester/dropbox', to: 'tester#dropbox'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  devise_scope :user do get "users/sign_out" => 'devise/sessions#destroy' end
  get "sign_up", :to => "devise/registrations#new"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'documentation' => 'documentation/index'
  get 'contact' => 'contact/index'
  get "faq" => 'faq/index'
  get "how_to" => 'how_to/index'
  get 'reference' => 'reference/index'

  get '/i2x/images/*all', to: redirect('/images/%{all}.png')

end

app/controllers/helper_controller.rb
class HelperController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  ##
  # => Highlight variables and code for UI
  #
  def highlight_variables(text)

    # highlight variables
    highlighter = '<span class="selector">\1</span>'
    matcher = /%{(.*?)}/
    a = text.gsub(matcher, highlighter).html_safe

    # highlight code
    highlighter = '<span class="code">\1</span>'
    matcher = /\${(.*?)}/
    text = a.gsub(matcher, highlighter).html_safe
  end

  ##
  # => Automating tabindex counts
  #
  def autotab
    @current_tab ||= 0
    @current_tab += 1
  end

  ##
  # => Making Devise login/registration available everywhere
  #
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/views/helper/_event_list.html.erb
<h4 class="subheader">Events</h4>
<ul class="no-bullet">
	<% @events.each do |event| %>
	<li><%= link_to "#{event.agent.title}".truncate(10, :omission => "... ").html_safe, event, :class => 'icon-right' %> <span class="tiny label secondary radius"><%= time_ago_in_words(event.created_at) %> ago </span></li>
	<% end %>
</ul>

app/views/helper/_sidenav.html.erb
<!-- User logged in, display details and links to work areas -->
<% if user_signed_in? then %>
<ul class="off-canvas-list">
  <li><label><%=  current_user.name ||= current_user.username %></label></li>
  <li><%= link_to('Details'.html_safe, edit_user_registration_path, :class => 'icon-userdetails') %></li>
  <li><%= link_to('Sign Out'.html_safe, destroy_user_session_path, :method => :delete, :class => 'icon-signout') %></li>
</ul>
<br/>
<ul class="off-canvas-list">
  <li><label>Go To</label></li>
  <li><%= link_to 'Dashboard'.html_safe, {:controller => '/integrations'}, :class => 'icon-integration', :title => 'Go to Dashboard' %></li>
  <li><%= link_to 'Agents'.html_safe, {:controller => '/agents'}, :class => 'icon-agent', :title => 'Go to Agents'%></li>
  <li><%= link_to 'Templates', {:controller => '/templates'}, :class => 'icon-template', :title => 'Go to Templates' %></li>
  <li><%= link_to 'Files', {:controller => '/files', :action => 'index'}, :class => 'icon-files', :title => 'Go to Files' %></li>
</ul>
<!-- User not logged in, display login and social authentication links -->
<% else %>
<ul class="off-canvas-list">
  <li><label>Login</label></li>
  <li>
     <%= form_for("user", :url => user_session_path, :html => {:novalidate => true}) do |f| %>
    <div class="row">
      <div class="small-12">
        <%= f.text_field :login, :placeholder => 'Login' %>
      </div>
      <div class="small-12">
        <%= f.password_field :password, :placeholder => 'Password' %>
      </div>
      <div class="small-12">
        <span class="user-side-text left mg-right">Remember me?</span>
        <%= f.check_box :remember_me, :checked => true, :class => 'left remember_me' %>
        <%= f.submit 'Sign in', :class => 'button tiny radius right mg-right' %>
      </div>
      <div class="right">
        <%= link_to "<small>Forgot your password?</small>".html_safe, new_password_path('user'), :class => 'right' %>
      </div>
    </div>
    <% end %></li>
    <li><label><%= link_to('Sign up'.html_safe, new_user_registration_path, :class => 'icon-signup')  %></label></li>
    <li>
      <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "", omniauth_authorize_path('user', provider), :class => "no-block icon-#{provider}" %>
      <% end -%>
    </li>    
  </ul>
  <%end %>

app/views/helper/index.html.erb
<h1>Helper#index</h1>
<p>Find me in app/views/helper/index.html.erb</p>