config/routes.rb
I2X::Application.routes.draw do

  root  'home#index'
  get 'home' => 'home/index'
  get "home/index"

  get "about/index"

  resources :agents
  get "agents/partials/:identifier", to: 'agents#partials'  		# what is this?
  get "agents/import/:identifier", to: "agents#import"      		# import from JSON file
  get "agents/:id/get", to: "agents#get"            		        # load agent as JSON
  get "agents/add/:identifier", to: "agents#add"            		# add sample agent to user
  get "agents/:id/execute", to: "agents#execute"                # launch on-demand agent execution
  
  
  resources :caches

  get "contact/index", to: 'contact#index'

  get 'dashboard',to: redirect('/integrations')

  get "delivery/get"
  post "delivery/post"
  get "delivery/go"

  get "docs", to: 'docs#index'
  get 'docs/:section/:topic', to: 'docs#show'

  resources :events
  resources :events do
    get 'page/:page', :action => :index, :on => :collection
  end

  get "files/get/:filename", to: "files#get"
  get "files/delete/:filename", to: "files#delete"
  get "files/index"

  post "fluxcapacitor/generate_key", to: 'flux_capacitor#generate_key'
  post "fluxcapacitor/remove_key", to: 'flux_capacitor#remove_key'
  post "fluxcapacitor/validate_key", to: 'flux_capacitor#validate_key'
  post 'fluxcapacitor/verify', to: 'flux_capacitor#verify'
  get 'fluxcapacitor/ping/:ping', to: 'flux_capacitor#ping'
  post 'fluxcapacitor/ping', to: 'flux_capacitor#ping'
  post 'fluxcapacitor/generate_client', to: 'flux_capacitor#generate_client'
  get 'fluxcapacitor/generate_client', to: 'flux_capacitor#generate_client'
  post 'fluxcapacitor/agents/:id/update_meta', to: 'flux_capacitor#agent_update_meta'
  
  get "helper/index"

  resources :integrations
  post "integrations/:id/save", to: 'integrations#save'
  get "integrations/add/:agent/:template", to: 'integrations#add'
  get "integrations/:id/execute", to: 'integrations#execute'      # execute integration on-demand

  get "postman/load/:publisher/:identifier", to: "postman#load"
  get "postman/go/:identifier", to: 'postman#go'
  post "postman/deliver/:identifier", to: "postman#deliver"
  post "postman/:key", to: "postman#action"

  post "push/:identifier", to: "push#checkup"

  resources :seeds

  resources :templates
  get "templates/:id/get", to: "templates#get"            # load template as JSON
  post "templates/new"
  get "templates/start"
  get "templates/add/:identifier", to: 'templates#add'            # add template from samples to user
  

  get "tester/regex", to: 'tester#regex'
  get "tester/agent/:identifier", to: 'tester#agent'
  get 'tester/dropbox', to: 'tester#dropbox'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  devise_scope :user do get "users/sign_out" => 'devise/sessions#destroy' end
  get "sign_up", :to => "devise/registrations#new"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'documentation' => 'documentation/index'
  get 'contact' => 'contact/index'
  get "faq" => 'faq/index'
  get "how_to" => 'how_to/index'
  get 'reference' => 'reference/index'

  get '/i2x/images/*all', to: redirect('/images/%{all}.png')

end

app/controllers/caches_controller.rb
class CachesController < ApplicationController
  before_action :set_cach, only: [:show, :edit, :update, :destroy]

  # GET /caches
  # GET /caches.json
  def index
    @caches = Cache.all
  end

  # GET /caches/1
  # GET /caches/1.json
  def show
  end

  # GET /caches/new
  def new
    @cach = Cache.new
  end

  # GET /caches/1/edit
  def edit
  end

  # POST /caches
  # POST /caches.json
  def create
    @cach = Cache.new(cach_params)

    respond_to do |format|
      if @cach.save
        format.html { redirect_to @cach, notice: 'Cache was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cach }
      else
        format.html { render action: 'new' }
        format.json { render json: @cach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caches/1
  # PATCH/PUT /caches/1.json
  def update
    respond_to do |format|
      if @cach.update(cach_params)
        format.html { redirect_to @cach, notice: 'Cache was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caches/1
  # DELETE /caches/1.json
  def destroy
    @cach.destroy
    respond_to do |format|
      format.html { redirect_to caches_url }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cach
    @cach = Cache.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cach_params
    params.require(:cach).permit(:hash, :publisher, :agent, :payload, :memory)
  end
end

app/views/caches/_form.html.erb
<%= form_for(@cach) do |f| %>
  <% if @cach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cach.errors.count, "error") %> prohibited this cach from being saved:</h2>

      <ul>
      <% @cach.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hash %><br>
    <%= f.text_field :hash %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :agent %><br>
    <%= f.text_field :agent %>
  </div>
  <div class="field">
    <%= f.label :payload %><br>
    <%= f.text_area :payload %>
  </div>
  <div class="field">
    <%= f.label :memory %><br>
    <%= f.text_area :memory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caches/edit.html.erb
<h1>Editing cach</h1>

<%= render 'form' %>

<%= link_to 'Show', @cach %> |
<%= link_to 'Back', caches_path %>

app/views/caches/index.html.erb
<h1>Listing caches</h1>

<table>
  <thead>
    <tr>
      <th>Hash</th>
      <th>Publisher</th>
      <th>Agent</th>
      <th>Payload</th>
      <th>Memory</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @caches.each do |cach| %>
      <tr>
        <td><%= cach.hash %></td>
        <td><%= cach.publisher %></td>
        <td><%= cach.agent %></td>
        <td><%= cach.payload %></td>
        <td><%= cach.memory %></td>
        <td><%= link_to 'Show', cach %></td>
        <td><%= link_to 'Edit', edit_cach_path(cach) %></td>
        <td><%= link_to 'Destroy', cach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cache', new_cach_path %>

app/views/caches/new.html.erb
<h1>New cach</h1>

<%= render 'form' %>

<%= link_to 'Back', caches_path %>

app/views/caches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hash:</strong>
  <%= @cach.hash %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @cach.publisher %>
</p>

<p>
  <strong>Agent:</strong>
  <%= @cach.agent %>
</p>

<p>
  <strong>Payload:</strong>
  <%= @cach.payload %>
</p>

<p>
  <strong>Memory:</strong>
  <%= @cach.memory %>
</p>

<%= link_to 'Edit', edit_cach_path(@cach) %> |
<%= link_to 'Back', caches_path %>