config/routes.rb
I2X::Application.routes.draw do

  root  'home#index'
  get 'home' => 'home/index'
  get "home/index"

  get "about/index"

  resources :agents
  get "agents/partials/:identifier", to: 'agents#partials'  		# what is this?
  get "agents/import/:identifier", to: "agents#import"      		# import from JSON file
  get "agents/:id/get", to: "agents#get"            		        # load agent as JSON
  get "agents/add/:identifier", to: "agents#add"            		# add sample agent to user
  get "agents/:id/execute", to: "agents#execute"                # launch on-demand agent execution
  
  
  resources :caches

  get "contact/index", to: 'contact#index'

  get 'dashboard',to: redirect('/integrations')

  get "delivery/get"
  post "delivery/post"
  get "delivery/go"

  get "docs", to: 'docs#index'
  get 'docs/:section/:topic', to: 'docs#show'

  resources :events
  resources :events do
    get 'page/:page', :action => :index, :on => :collection
  end

  get "files/get/:filename", to: "files#get"
  get "files/delete/:filename", to: "files#delete"
  get "files/index"

  post "fluxcapacitor/generate_key", to: 'flux_capacitor#generate_key'
  post "fluxcapacitor/remove_key", to: 'flux_capacitor#remove_key'
  post "fluxcapacitor/validate_key", to: 'flux_capacitor#validate_key'
  post 'fluxcapacitor/verify', to: 'flux_capacitor#verify'
  get 'fluxcapacitor/ping/:ping', to: 'flux_capacitor#ping'
  post 'fluxcapacitor/ping', to: 'flux_capacitor#ping'
  post 'fluxcapacitor/generate_client', to: 'flux_capacitor#generate_client'
  get 'fluxcapacitor/generate_client', to: 'flux_capacitor#generate_client'
  post 'fluxcapacitor/agents/:id/update_meta', to: 'flux_capacitor#agent_update_meta'
  
  get "helper/index"

  resources :integrations
  post "integrations/:id/save", to: 'integrations#save'
  get "integrations/add/:agent/:template", to: 'integrations#add'
  get "integrations/:id/execute", to: 'integrations#execute'      # execute integration on-demand

  get "postman/load/:publisher/:identifier", to: "postman#load"
  get "postman/go/:identifier", to: 'postman#go'
  post "postman/deliver/:identifier", to: "postman#deliver"
  post "postman/:key", to: "postman#action"

  post "push/:identifier", to: "push#checkup"

  resources :seeds

  resources :templates
  get "templates/:id/get", to: "templates#get"            # load template as JSON
  post "templates/new"
  get "templates/start"
  get "templates/add/:identifier", to: 'templates#add'            # add template from samples to user
  

  get "tester/regex", to: 'tester#regex'
  get "tester/agent/:identifier", to: 'tester#agent'
  get 'tester/dropbox', to: 'tester#dropbox'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  devise_scope :user do get "users/sign_out" => 'devise/sessions#destroy' end
  get "sign_up", :to => "devise/registrations#new"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'documentation' => 'documentation/index'
  get 'contact' => 'contact/index'
  get "faq" => 'faq/index'
  get "how_to" => 'how_to/index'
  get 'reference' => 'reference/index'

  get '/i2x/images/*all', to: redirect('/images/%{all}.png')

end

app/controllers/files_controller.rb
class FilesController < ApplicationController
	before_filter :authenticate_user!

	def get		
		begin
			send_file "data/users/#{current_user.id}/#{params[:filename]}.#{params[:format]}",
			:filename => "#{params[:filename]}.#{params[:format]}"		
		rescue Exception => e
			Services::Slog.exception e
		end
	end

	def delete	
		begin
			File.delete("data/users/#{current_user.id}/#{params[:filename]}.#{params[:format]}")
		rescue Exception => e
			Services::Slog.exception e
		end
		redirect_to action: 'index'
	end

	def index
		@events = Event.by_user_limit current_user
		@files = Dir["data/users/#{current_user.id}/*"]	
	end
end

app/views/files/delete.html.erb
<h1>Files#get</h1>
<p>Find me in app/views/files/get.html.erb</p>

app/views/files/get.html.erb
<h1>Files#get</h1>
<p>Find me in app/views/files/get.html.erb</p>

app/views/files/index.html.erb
<% content_for :title, "Files - #{ENV["APP_TITLE"]}" %>
<ul class="breadcrumbs">
	<li><a href="<%= root_url %>">Home</a></li>
	<li class="current">Files</li>
</ul>
<h1>Files</h1>
<!-- main content -->
<% unless flash[:notice].nil? then %>
<div data-alert class="alert-box warning radius">
	<%= flash[:notice].html_safe %>
	<a href="#" class="close">&times;</a>
</div>
<% end %>
<div class="small-9 columns">
	<table>
		<thead>
			<th>Filename</th><th>Actions</th>
		</thead>
		<tbody>
			<% @files.each do |file| %>
			<tr>
				<td><a href="<%= "../files/get/#{File.basename(file)}" %>"><%= File.basename(file) %></a></td>
				<td class="right"><a href="<%= "../files/get/#{File.basename(file)}" %>" class="icon-download"></a> <a href="<%= "../files/delete/#{File.basename(file)}" %>" class="icon-delete"></a></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="small-3 columns">
	<% if current_user.agents.empty? %>
	<%= link_to 'New Agent', new_agent_path, :title => 'Create new agent', :class => 'button small radius icon-agent', :data => { :tooltip => ''} %>
	<% else %>
	<% if current_user.templates.empty? %>
	<%= link_to ' New Template', new_template_path, :class => 'button small radius icon-template' %>
	<% else %>
	<%= link_to ' New Integration'.html_safe, new_integration_path, :class => 'button small radius icon-integration' %>
	<% end %>
	<% end %>
	<h4>Go to</h4>
	<ul class="no-bullet">
		<li><%= link_to 'Agents'.html_safe, {:controller => '/agents'}, :class => 'icon-agent'%></li>
		<li><%= link_to 'Templates'.html_safe, {:controller => '/templates'}, :class => 'icon-template'%></li>
		<li><%= link_to 'Files', {:controller => '/files', :action => 'index'}, :class => 'icon-files' %></li>
	</ul>
	<%= render partial: "helper/event_list"  %>
</div>